export const ADD_HANDLE = 'ADD_HANDLE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const USER_SELECTED = 'USER_SELECTED';
export const USER_SELECTED_CHAT = 'USER_SELECTED_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_LAST_ID = 'UPDATE_LAST_ID';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
